# Recommendation systems

Intelligent System for Industrial Problem Detection and Corrective Recommendations

## üî∂ Step 1: Data Preparation and Merging

In [5]:
import pandas as pd
import os

# R√©pertoire contenant vos fichiers CSV
repertoire_csv = 'projet'

# Lister les fichiers CSV dans le r√©pertoire
fichiers_csv = [f for f in os.listdir(repertoire_csv) if f.endswith('.csv')]

# Dictionnaire pour stocker les DataFrames
dataframes = {}

# Charger chaque fichier CSV dans un DataFrame
for fichier in fichiers_csv:
    # Construire le chemin complet du fichier
    chemin_fichier = os.path.join(repertoire_csv, fichier)
    try:
        # Charger le CSV dans un DataFrame
        df = pd.read_csv(chemin_fichier, sep=';', encoding='utf-8', skipinitialspace=True)
        # Ajouter le DataFrame au dictionnaire
        nom_table = os.path.splitext(fichier)[0]
        dataframes[nom_table] = df
        # Afficher les premi√®res lignes du DataFrame
        print(f"Table '{nom_table}' charg√©e avec succ√®s:")
        display(df.head())  # Utilisez display() pour une meilleure pr√©sentation dans Jupyter
        print("\n")
    except Exception as e:
        print(f"Erreur lors du chargement de '{fichier}': {e}")

Table 'Dim_Brand' charg√©e avec succ√®s:

   Pk_Brand BrandCode    marque
0         1     BR001    Danone
1         2     BR002  Lactalis
2         3     BR003    Nestle
3         4     BR004  Industry

Table 'Dim_Category_Equipment' charg√©e avec succ√®s:

   pk_category CategoryCode          Category
0            1        CT001   Conditionnement
1            2        CT002  Contr√¥le Qualit√©
2            3        CT003         Nettoyage
3            4        CT004    Transformation
4            5        CT005     R√©frig√©ration

Table 'Dim_Date' charg√©e avec succ√®s:

   Pk_Date    FullDate  Day  Month  Year
0        1  2023-01-05    5      1  2023
1        2  2023-01-06    6      1  2023
2        3  2023-01-07    7      1  2023
3        4  2023-01-08    8      1  2023
4        5  2023-01-09    9      1  2023

Table 'Dim_Equipment' charg√©e avec succ√®s:

,Pk_Equipment,Equipment_ID,Equipment_Name,Fk_Mfrequency,Fk_MCycle,Fk_Category,Fk_Energy,Manufacturer,Estimated_Lifetime_Years
0,1,E4861,Machine d'Inspection Visuelle,1,1,1,1,AgroTech Inc.,17
1,2,E10000,Cuve de Maturation,1,2,2,1,EvapoTech Co.,12
2,3,E10001,Machine d'Inspection Visuelle,1,1,3,2,PackEquip SARL,12
3,4,E3003,Syst√®me de Nettoyage CIP,1,2,1,2,RoboPack Inc.,12
4,5,E7501,Robot de Palettisation,1,3,1,1,CleanTech Solutions,8

Table 'Dim_Location' charg√©e avec succ√®s:

   Pk_Location LocationCode Location
0            1         L001   Nabeul
1            2         L002   Sousse
2            3         L003    Gab√®s
3            4         L004     Sfax
4            5         L005    Tunis

Table 'Dim_Maintenance_Cycle' charg√©e avec succ√®s:

   Pk_MCycle MCycleCode Maintenance_Cycle
0          1      MC001       Bimensuelle
1          2      MC002      Annuellement
2          3      MC003     Trimestrielle
3          4      MC004         Mensuelle
4          5      MC005      Hebdomadaire

Table 'Dim_Maintenance_Frequency' charg√©e avec succ√®s:

   Pk_Mfrequency FrequencyCode Maintenance_Frequency
0              1         MF001                Annuel
1              2         MF002               Mensuel
2              3         MF003           Trimestriel

Table 'Dim_Material' charg√©e avec succ√®s:

,Pk_Material,MaterialCode,Material_name,Fk_Type_MM,Recycled_Packaging
0,1,M090,Ferments lactiques,1,Non
1,2,M086,Ferments lactiques,1,Oui
2,3,M102,Concentr√É¬© de fraise,1,Oui
3,4,M011,Ferments lactiques,1,Oui
4,5,M491,Ferments lactiques,2,Non

Table 'Dim_Notif_Type' charg√©e avec succ√®s:

   PK_Notif_Type NotificationCode
0              1               M3
1              2               M2
2              3               M1

Table 'Dim_Stock_Type' charg√©e avec succ√®s:

   Pk_Stock_Type StockCode Stock_Type
0              1     ST001  HighValue
1              2     ST002   LowValue
2              3     ST003   Standard

Table 'Dim_Supplier' charg√©e avec succ√®s:

,Pk_Supplier,Fk_Type_Transport,SupplierCode,Supplier_Name,Environmental_Certifications,Sustainability_Program
0,1,1,SUPPLIER_1,Laiterie Centrale,Agriculture Biologique,Oui
1,2,1,SUPPLIER_2,Agro-Alimentaire Tunisie,Aucune,Non
2,3,1,SUPPLIER_3,Import-Export Naturel,ISO 14001,Non
3,4,1,SUPPLIER_4,Qualit√© Fra√Æcheur,Aucune,Non
4,5,1,SUPPLIER_5,Fruits et Saveurs,Aucune,Oui

Table 'Dim_Transport_Type' charg√©e avec succ√®s:

   Pk_transport TransportCode Transport_Type
0             1         TT001        Unknown
1             2         TT002    Ferroviaire
2             3         TT003     Multimodal
3             4         TT004         A√©rien
4             5         TT005       Maritime

Table 'Dim_Type_Energy' charg√©e avec succ√®s:

   Pk_energy EnergyCode  Energy_Type
0          1      EN001      Solaire
1          2      EN002        Fioul
2          3      EN003          Gaz
3          4      EN004  Electricit√©

Table 'Dim_Type_MM' charg√©e avec succ√®s:

   Pk_Type_MM TypeMMCode             Type
0           1     TMM001  Produit laitier
1           2     TMM002      Ingr√É¬©dient
2           3     TMM003              NaN

Table 'Dim_Usine_Stock' charg√©e avec succ√®s:

   Pk_usine UsineCode
0         1    PLANT1
1         2    PLANT2
2         3    PLANT3

Table 'Fact_Co2_Emissions' charg√©e avec succ√®s:

,Fk_Date,Fk_Equipment,Fk_Material,Fk_Location,Fk_Brand,Fk_Supplier,Carbon_Foot_Print_per_Unit_kgCo2,Transport_Distance_Km,Water_Consumption_PerUnit_L,CO2_Emissions_kg_equipment,Temperature,Humidity,Wind_Speed,CO2_Ambient_Level,Energy_Consumption_kWh,Renewable_Energy_Percentage
0,401,325,668,2,4,37,383,300,1149,"255,8817",21,98,"12,3","361,66","4407,226","5,31"
1,401,325,668,3,4,37,383,300,1149,"255,8817","28,65",27,12,432220,"4407,226","5,31"
2,401,325,668,4,4,37,383,300,1149,"255,8817","41,6",90,"3,4","468,77","4407,226","5,31"
3,401,325,668,5,4,37,383,300,1149,"255,8817","19,6",41,"0,8","479,47","4407,226","5,31"
4,401,325,1871,2,4,37,383,300,1149,"255,8817",21,98,"12,3","361,66","4407,226","5,31"

Table 'Fact_MM_PM' charg√©e avec succ√®s:

,Fk_Equipment,Fk_Material,Fk_Location,Fk_Date_Creation_Notification,Fk_Date_limite_resolution_Notif,FK_Notif_Type,Fk_usine,Fk_Stock_Type,Total_Stock,Input_stock,Output_Stock,Blocked_stock,Prioryty
0,24,430,3,649,509,3,1,1,593,49,6,4,4.0
1,24,430,3,649,509,3,2,3,546,18,6,9,4.0
2,24,430,4,649,509,3,1,3,961,37,19,3,4.0
3,24,430,4,649,509,3,2,2,908,34,18,5,4.0
4,24,430,4,649,509,3,3,2,711,27,0,9,4.0

In [7]:
# Raccourcis pour les tables importantes
fact_co2 = dataframes['Fact_Co2_Emissions']
fact_mm_pm = dataframes['Fact_MM_PM']
equipements = dataframes['Dim_Equipment']
fournisseurs = dataframes['Dim_Supplier']
materiaux = dataframes['Dim_Material']
energie = dataframes['Dim_Type_Energy']
transport = dataframes['Dim_Transport_Type']
type_mm = dataframes['Dim_Type_MM']
cat_eq=dataframes['Dim_Category_Equipment']

# Fusion avec les dimensions pertinentes pour enrichir les donn√©es CO2
df_merged = fact_co2.merge(equipements, left_on='Fk_Equipment', right_on='Pk_Equipment', how='left')
df_merged = df_merged.merge(energie, left_on='Fk_Energy', right_on='Pk_energy', how='left')
df_merged = df_merged.merge(fournisseurs, left_on='Fk_Supplier', right_on='Pk_Supplier', how='left')
df_merged = df_merged.merge(transport, left_on='Fk_Type_Transport', right_on='Pk_transport', how='left')
df_merged = df_merged.merge(materiaux, left_on='Fk_Material', right_on='Pk_Material', how='left')
df_merged = df_merged.merge(type_mm, left_on='Fk_Type_MM', right_on='Pk_Type_MM', how='left')
df_merged = df_merged.merge(cat_eq, left_on='Fk_Category', right_on='pk_category', how='left')

# Ajout de la table Fact_MM_PM : m√™me √©quipement et m√™me mati√®re
df_merged = df_merged.merge(
    fact_mm_pm,
    on=['Fk_Equipment', 'Fk_Material'],
    how='left',
    suffixes=('', '_mm_pm')  # pour √©viter les collisions de colonnes
)
print("‚úÖ Donn√©es enrichies AVEC consommation mati√®re/PM pr√™tes pour l'analyse.")
display(df_merged.head())

print("‚úÖ Donn√©es enrichies pr√™tes pour l'analyse.")
display(df_merged.head())

‚úÖ Donn√©es enrichies AVEC consommation mati√®re/PM pr√™tes pour l'analyse.

,Fk_Date,Fk_Equipment,Fk_Material,Fk_Location,Fk_Brand,Fk_Supplier,Carbon_Foot_Print_per_Unit_kgCo2,Transport_Distance_Km,Water_Consumption_PerUnit_L,CO2_Emissions_kg_equipment,...,Fk_Date_Creation_Notification,Fk_Date_limite_resolution_Notif,FK_Notif_Type,Fk_usine,Fk_Stock_Type,Total_Stock,Input_stock,Output_Stock,Blocked_stock,Prioryty
0,401,325,668,2,4,37,383,300,1149,"255,8817",...,437,408,3,2,2,237,6,6,8,4.0
1,401,325,668,2,4,37,383,300,1149,"255,8817",...,437,408,3,3,2,694,18,18,2,4.0
2,401,325,668,2,4,37,383,300,1149,"255,8817",...,437,408,3,2,3,748,38,16,7,4.0
3,401,325,668,2,4,37,383,300,1149,"255,8817",...,437,408,3,3,1,792,6,16,0,4.0
4,401,325,668,2,4,37,383,300,1149,"255,8817",...,437,408,3,3,3,304,3,9,2,4.0

‚úÖ Donn√©es enrichies pr√™tes pour l'analyse.

,Fk_Date,Fk_Equipment,Fk_Material,Fk_Location,Fk_Brand,Fk_Supplier,Carbon_Foot_Print_per_Unit_kgCo2,Transport_Distance_Km,Water_Consumption_PerUnit_L,CO2_Emissions_kg_equipment,...,Fk_Date_Creation_Notification,Fk_Date_limite_resolution_Notif,FK_Notif_Type,Fk_usine,Fk_Stock_Type,Total_Stock,Input_stock,Output_Stock,Blocked_stock,Prioryty
0,401,325,668,2,4,37,383,300,1149,"255,8817",...,437,408,3,2,2,237,6,6,8,4.0
1,401,325,668,2,4,37,383,300,1149,"255,8817",...,437,408,3,3,2,694,18,18,2,4.0
2,401,325,668,2,4,37,383,300,1149,"255,8817",...,437,408,3,2,3,748,38,16,7,4.0
3,401,325,668,2,4,37,383,300,1149,"255,8817",...,437,408,3,3,1,792,6,16,0,4.0
4,401,325,668,2,4,37,383,300,1149,"255,8817",...,437,408,3,3,3,304,3,9,2,4.0

In [9]:
# Raccourcis pour les tables suppl√©mentaires
maintenance_cycle = dataframes['Dim_Maintenance_Cycle']
category_equipment = dataframes['Dim_Category_Equipment']

# Fusionner les donn√©es
df_merged = df_merged.merge(
    maintenance_cycle,
    left_on='Fk_MCycle',  # Cl√© √©trang√®re dans Dim_Equipment
    right_on='Pk_MCycle',  # Cl√© primaire dans Dim_Maintenance_Cycle
    how='left'
)

df_merged = df_merged.merge(
    category_equipment,
    left_on='Fk_Category',  # Cl√© √©trang√®re dans Dim_Equipment
    right_on='pk_category', # Cl√© primaire dans Dim_Category_Equipment
    how='left'
)

# V√©rifier les colonnes disponibles
print("Colonnes dans df_merged :", df_merged.columns.tolist())

Colonnes dans df_merged : ['Fk_Date', 'Fk_Equipment', 'Fk_Material', 'Fk_Location', 'Fk_Brand', 'Fk_Supplier', 'Carbon_Foot_Print_per_Unit_kgCo2', 'Transport_Distance_Km', 'Water_Consumption_PerUnit_L', 'CO2_Emissions_kg_equipment', 'Temperature', 'Humidity', 'Wind_Speed', 'CO2_Ambient_Level', 'Energy_Consumption_kWh', 'Renewable_Energy_Percentage', 'Pk_Equipment', 'Equipment_ID', 'Equipment_Name', 'Fk_Mfrequency', 'Fk_MCycle', 'Fk_Category', 'Fk_Energy', 'Manufacturer', 'Estimated_Lifetime_Years', 'Pk_energy', 'EnergyCode', 'Energy_Type', 'Pk_Supplier', 'Fk_Type_Transport', 'SupplierCode', 'Supplier_Name', 'Environmental_Certifications', 'Sustainability_Program', 'Pk_transport', 'TransportCode', 'Transport_Type', 'Pk_Material', 'MaterialCode', 'Material_name', 'Fk_Type_MM', 'Recycled_Packaging', 'Pk_Type_MM', 'TypeMMCode', 'Type', 'pk_category_x', 'CategoryCode_x', 'Category_x', 'Fk_Location_mm_pm', 'Fk_Date_Creation_Notification', 'Fk_Date_limite_resolution_Notif', 'FK_Notif_Type', 'Fk_usine', 'Fk_Stock_Type', 'Total_Stock', 'Input_stock', 'Output_Stock', 'Blocked_stock', 'Prioryty', 'Pk_MCycle', 'MCycleCode', 'Maintenance_Cycle', 'pk_category_y', 'CategoryCode_y', 'Category_y']

In [11]:
df_merged = df_merged.rename(columns={
    "Category_y": "Category_Equipment"
})
colonnes_a_corriger = [
    "Renewable_Energy_Percentage",
    "CO2_Emissions_kg_equipment",
    "Carbon_Foot_Print_per_Unit_kgCo2",
    "Water_Consumption_PerUnit_L",
    "Energy_Consumption_kWh",
    "Temperature", 
    "Wind_Speed", 
    "CO2_Ambient_Level", 
    "Energy_Consumption_kWh",
    "Transport_Distance_Km"
]

for col in colonnes_a_corriger:
    df_merged[col] = df_merged[col].astype(str).str.replace(",", ".").astype(float)

In [13]:
# Calculer Transport_CO2 (adapt√© de votre DAX)
def calculate_transport_co2(row):
    transport_factors = {
        1: 0.1,    # Unknown
        2: 0.03,   # Ferroviaire
        3: 0.1,    # Multimodal
        4: 0.15,   # A√©rien
        5: 0.05,   # Maritime
        6: 0.2     # Camionnage
    }
    transport_type = row['Fk_Type_Transport']
    distance = row['Transport_Distance_Km']
    return distance * transport_factors.get(transport_type, 0)

df_merged['Transport_CO2'] = df_merged.apply(calculate_transport_co2, axis=1)

In [14]:
# Eau consomm√©e par unit√© produite
df_merged['Water_Per_Unit'] = df_merged.apply(
    lambda row: row['Water_Consumption_PerUnit_L'] / row['Total_Stock']
    if row['Total_Stock'] > 0 else 0, axis=1)

# CO2 par kWh
df_merged['CO2_kg_per_kWh'] = df_merged.apply(
    lambda row: row['CO2_Emissions_kg_equipment'] / row['Energy_Consumption_kWh']
    if row['Energy_Consumption_kWh'] > 0 else 0, axis=1)

# CO2 par unit√© de mati√®re (pour une marque sp√©cifique)
df_merged['CO2_Per_Unit_Material_kg'] = df_merged.apply(
    lambda row: row['Carbon_Foot_Print_per_Unit_kgCo2'] / row['Total_Stock']
    if row['Fk_Brand'] == 4 and row['Total_Stock'] > 0 else 0, axis=1)

# Score de durabilit√© fournisseur (plus le score est √©lev√©, mieux c'est)
df_merged['Supplier_Sustainability_Score'] = df_merged.apply(
    lambda row: max(0, (1 - (
        row['Transport_CO2'] / (
            row['CO2_Emissions_kg_equipment'] +
            row['Carbon_Foot_Print_per_Unit_kgCo2'] +
            row['CO2_Ambient_Level']
        )) * 100)
    ) if row['Fk_Brand'] == 4 and (
        row['CO2_Emissions_kg_equipment'] +
        row['Carbon_Foot_Print_per_Unit_kgCo2'] +
        row['CO2_Ambient_Level']
    ) > 0 else 0,
    axis=1)

In [16]:
display(df_merged.head())

,Fk_Date,Fk_Equipment,Fk_Material,Fk_Location,Fk_Brand,Fk_Supplier,Carbon_Foot_Print_per_Unit_kgCo2,Transport_Distance_Km,Water_Consumption_PerUnit_L,CO2_Emissions_kg_equipment,...,MCycleCode,Maintenance_Cycle,pk_category_y,CategoryCode_y,Category_Equipment,Transport_CO2,Water_Per_Unit,CO2_kg_per_kWh,CO2_Per_Unit_Material_kg,Supplier_Sustainability_Score
0,401,325,668,2,4,37,383.0,300.0,1149.0,255.8817,...,MC001,Bimensuelle,6,CT006,Production,15.0,4.848101,0.05806,1.616034,0.0
1,401,325,668,2,4,37,383.0,300.0,1149.0,255.8817,...,MC001,Bimensuelle,6,CT006,Production,15.0,1.655620,0.05806,0.551873,0.0
2,401,325,668,2,4,37,383.0,300.0,1149.0,255.8817,...,MC001,Bimensuelle,6,CT006,Production,15.0,1.536096,0.05806,0.512032,0.0
3,401,325,668,2,4,37,383.0,300.0,1149.0,255.8817,...,MC001,Bimensuelle,6,CT006,Production,15.0,1.450758,0.05806,0.483586,0.0
4,401,325,668,2,4,37,383.0,300.0,1149.0,255.8817,...,MC001,Bimensuelle,6,CT006,Production,15.0,3.779605,0.05806,1.259868,0.0

In [17]:
df_merged.columns

Index(['Fk_Date', 'Fk_Equipment', 'Fk_Material', 'Fk_Location', 'Fk_Brand',
       'Fk_Supplier', 'Carbon_Foot_Print_per_Unit_kgCo2',
       'Transport_Distance_Km', 'Water_Consumption_PerUnit_L',
       'CO2_Emissions_kg_equipment', 'Temperature', 'Humidity', 'Wind_Speed',
       'CO2_Ambient_Level', 'Energy_Consumption_kWh',
       'Renewable_Energy_Percentage', 'Pk_Equipment', 'Equipment_ID',
       'Equipment_Name', 'Fk_Mfrequency', 'Fk_MCycle', 'Fk_Category',
       'Fk_Energy', 'Manufacturer', 'Estimated_Lifetime_Years', 'Pk_energy',
       'EnergyCode', 'Energy_Type', 'Pk_Supplier', 'Fk_Type_Transport',
       'SupplierCode', 'Supplier_Name', 'Environmental_Certifications',
       'Sustainability_Program', 'Pk_transport', 'TransportCode',
       'Transport_Type', 'Pk_Material', 'MaterialCode', 'Material_name',
       'Fk_Type_MM', 'Recycled_Packaging', 'Pk_Type_MM', 'TypeMMCode', 'Type',
       'pk_category_x', 'CategoryCode_x', 'Category_x', 'Fk_Location_mm_pm',
       'Fk_Date_Creation_Notification', 'Fk_Date_limite_resolution_Notif',
       'FK_Notif_Type', 'Fk_usine', 'Fk_Stock_Type', 'Total_Stock',
       'Input_stock', 'Output_Stock', 'Blocked_stock', 'Prioryty', 'Pk_MCycle',
       'MCycleCode', 'Maintenance_Cycle', 'pk_category_y', 'CategoryCode_y',
       'Category_Equipment', 'Transport_CO2', 'Water_Per_Unit',
       'CO2_kg_per_kWh', 'CO2_Per_Unit_Material_kg',
       'Supplier_Sustainability_Score'],
      dtype='object')

## üî∂ Step 2: Problem Knowledge Base (Referential)

In [22]:
problemes_referentiel = [
    # Equipements par type d'√©nergie
    {
        "Categorie": "Equipement",
        "Sous-categorie": "Fioul",
        "Indicateurs": ["CO2_Emissions_kg_equipment", "Energy_Consumption_kWh"],
        "Seuils": {"CO2_Emissions_kg_equipment": "> P95", "Energy_Consumption_kWh": "> P90"},
        "Actions": [
            "Conversion √† l'√©lectricit√© verte",
            "Optimisation combustion",
            "Installation de r√©cup√©rateurs de chaleur",
            "Remplacement urgent prioris√©"
        ],
        "Model_input": "equipement fioul consommation √©lev√©e"
    },
    {
        "Categorie": "Equipement",
        "Sous-categorie": "Gaz",
        "Indicateurs": ["CO2_Emissions_kg_equipment", "Temperature"],
        "Seuils": {"CO2_Emissions_kg_equipment": "> P90", "Temperature": "> P90 (surdimensionn√©)"},
        "Actions": [
            "Pilotage intelligent des temp√©ratures",
            "Isolation des r√©seaux",
            "Thermostats connect√©s",
            "Conversion partielle biogaz"
        ],
        "Model_input": "equipement gaz surconsommation"
    },
    
    # Processus de production
    {
        "Categorie": "Processus",
        "Sous-categorie": "Conditionnement",
        "Indicateurs": ["Energy_Consumption_kWh", "Water_Consumption_PerUnit_L"],
        "Seuils": {"Energy_Consumption_kWh": "> P85", "Water_Consumption_PerUnit_L": "> P75"},
        "Actions": [
            "Optimisation des cadences",
            "Nettoyage √† sec",
            "Recyclage des emballages d√©fectueux",
            "Automatisation des contr√¥les"
        ],
        "Model_input": "processus conditionnement ressources"
    },
    {
        "Categorie": "Processus",
        "Sous-categorie": "Contr√¥le Qualit√©",
        "Indicateurs": ["Blocked_stock", "CO2_Emissions_kg_equipment"],
        "Seuils": {"Blocked_stock": "> 5% du total", "CO2_Emissions_kg_equipment": "> P80"},
        "Actions": [
            "Contr√¥les non destructifs",
            "√âchantillonnage optimis√©",
            "Capteurs en ligne",
            "IA pour tri automatique"
        ],
        "Model_input": "processus contr√¥le qualit√© gaspillage"
    },
    {
        "Categorie": "Processus",
        "Sous-categorie": "Nettoyage",
        "Indicateurs": ["Water_Consumption_PerUnit_L", "Energy_Consumption_kWh"],
        "Seuils": {"Water_Consumption_PerUnit_L": "> 2x r√©f√©rence", "Energy_Consumption_kWh": "> P90"},
        "Actions": [
            "Nettoyage enzymatique",
            "Recyclage des effluents",
            "Optimisation des cycles CIP",
            "Formation op√©rateurs"
        ],
        "Model_input": "processus nettoyage intensif"
    },
    {
        "Categorie": "Processus",
        "Sous-categorie": "Transformation",
        "Indicateurs": ["CO2_Emissions_kg_equipment", "Temperature"],
        "Seuils": {"CO2_Emissions_kg_equipment": "> P95", "Temperature": "> P90 (√©carts)"},
        "Actions": [
            "R√©cup√©ration chaleur fatale",
            "Pr√©chauffage par √©changeurs",
            "Optimisation des param√®tres",
            "Maintenance fours/chaudi√®res"
        ],
        "Model_input": "processus transformation √©nergivore"
    },
    {
        "Categorie": "Processus",
        "Sous-categorie": "R√©frig√©ration",
        "Indicateurs": ["Energy_Consumption_kWh", "Humidity"],
        "Seuils": {"Energy_Consumption_kWh": "> P95", "Humidity": "< P10 (trop sec)"},
        "Actions": [
            "Optimisation plages horaires",
            "Contr√¥le hygrom√©trie",
            "Portes automatiques",
            "Compresseurs haute efficacit√©"
        ],
        "Model_input": "processus r√©frig√©ration humidit√©"
    },
    
    # Types de produits
    {
        "Categorie": "Produit",
        "Sous-categorie": "Produit laitier",
        "Indicateurs": ["Carbon_Foot_Print_per_Unit_kgCo2", "Transport_Distance_Km"],
        "Seuils": {"Carbon_Foot_Print_per_Unit_kgCo2": "> P90", "Transport_Distance_Km": "> 200km"},
        "Actions": [
            "Localisation approvisionnement",
            "Optimisation recettes",
            "Valorisation coproduits",
            "Emballages biod√©gradables"
        ],
        "Model_input": "produit laitier empreinte √©lev√©e"
    },
    {
        "Categorie": "Produit",
        "Sous-categorie": "Ingr√©dient",
        "Indicateurs": ["Water_Consumption_PerUnit_L", "Recycled_Packaging"],
        "Seuils": {"Water_Consumption_PerUnit_L": "> P90", "Recycled_Packaging": "== Non"},
        "Actions": [
            "Concentration des ingr√©dients",
            "Emballages bulk",
            "Fournisseurs certifi√©s",
            "Optimisation dosage"
        ],
        "Model_input": "ingr√©dient eau emballage"
    },
    
    # Solutions √©nerg√©tiques
    {
        "Categorie": "Energie",
        "Sous-categorie": "Solaire",
        "Indicateurs": ["Renewable_Energy_Percentage", "Energy_Consumption_kWh"],
        "Seuils": {"Renewable_Energy_Percentage": "< P10", "Energy_Consumption_kWh": "> P90"},
        "Actions": [
            "Installation panneaux suppl√©mentaires",
            "Contrats PPA solaire",
            "Stockage batterie",
            "Optimisation autoconsommation"
        ],
        "Model_input": "√©nergie solaire potentiel inexploit√©"
    },
    {
        "Categorie": "Energie",
        "Sous-categorie": "Electricit√©",
        "Indicateurs": ["Energy_Consumption_kWh", "CO2_Ambient_Level"],
        "Seuils": {"Energy_Consumption_kWh": "> P90", "CO2_Ambient_Level": "> 500ppm"},
        "Actions": [
            "Audit des pointes de consommation",
            "D√©calage des op√©rations √©nergivores",
            "Variateurs de fr√©quence",
            "LED et moteurs haute efficacit√©"
        ],
        "Model_input": "√©lectricit√© optimisation pic"
    },
# SCOPE 1 - √âmissions directes
    {
        "Categorie": "Scope1",
        "Sous-categorie": "Combustion_fixe",
        "Indicateurs": ["CO2_Emissions_kg_equipment", "Energy_Consumption_kWh"],
        "Seuils": {"CO2_Emissions_kg_equipment": "> 100kg/h", "Energy_Consumption_kWh": "> P95"},
        "Actions": [
            "Remplacement chaudi√®res fioul/gaz par biomasse",
            "Installation de syst√®mes de r√©cup√©ration de chaleur",
            "Optimisation des param√®tres de combustion",
            "Contr√¥le continu des √©missions"
        ],
        "Model_input": "scope1 combustion fixe chaudi√®re"
    },
    {
        "Categorie": "Scope1",
        "Sous-categorie": "Fugitives",
        "Indicateurs": ["CO2_Ambient_Level", "Temperature"],
        "Seuils": {"CO2_Ambient_Level": "> 800ppm", "Temperature": "< -10¬∞C (fuite possible)"},
        "Actions": [
            "D√©tection par cam√©ra infrarouge",
            "Remplacement gaz frigorig√®nes HFC",
            "Maintenance pr√©ventive circuits",
            "Formation manipulation gaz"
        ],
        "Model_input": "scope1 fuite gaz frigorig√®ne"
    },

    # SCOPE 2 - √âmissions indirectes √©nerg√©tiques
    {
        "Categorie": "Scope2",
        "Sous-categorie": "Electricite_achetee",
        "Indicateurs": ["Energy_Consumption_kWh", "Renewable_Energy_Percentage"],
        "Seuils": {"Energy_Consumption_kWh": "> P90", "Renewable_Energy_Percentage": "< 20%"},
        "Actions": [
            "N√©gociation contrat √©nergie verte",
            "Installation panneaux photovolta√Øques",
            "Syst√®me de monitoring √©nerg√©tique",
            "D√©calage op√©rations √©nergivores heures creuses"
        ],
        "Model_input": "scope2 √©lectricit√© grise"
    },
    {
        "Categorie": "Scope2",
        "Sous-categorie": "Vapeur_chauffage",
        "Indicateurs": ["Energy_Consumption_kWh", "Temperature"],
        "Seuils": {"Energy_Consumption_kWh": "> 500kWh/j", "Temperature": "> 120¬∞C (surdimensionn√©)"},
        "Actions": [
            "Isolation des r√©seaux vapeur",
            "R√©cup√©ration condensats",
            "Optimisation pression/temp√©rature",
            "Capteurs de fuite vapeur"
        ],
        "Model_input": "scope2 vapeur pertes √©nergie"
    },

    # SCOPE 3 - Autres √©missions indirectes
    {
        "Categorie": "Scope3",
        "Sous-categorie": "Achats_matieres",
        "Indicateurs": ["Carbon_Foot_Print_per_Unit_kgCo2", "Recycled_Packaging"],
        "Seuils": {"Carbon_Foot_Print_per_Unit_kgCo2": "> P90", "Recycled_Packaging": "== Non"},
        "Actions": [
            "Audit fournisseurs bas-carbone",
            "Sp√©cifications environnementales dans les appels d'offres",
            "Approvisionnement local",
            "Optimisation des formulations"
        ],
        "Model_input": "scope3 achats mati√®res premi√®res"
    },
    {
        "Categorie": "Scope3",
        "Sous-categorie": "Transport_amont",
        "Indicateurs": ["Transport_Distance_Km", "Transport_Type"],
        "Seuils": {"Transport_Distance_Km": "> 500km", "Transport_Type": "== A√©rien/Maritime"},
        "Actions": [
            "Report modal vers ferroviaire",
            "Optimisation planning livraisons",
            "Consolidation des chargements",
            "Collaboration logistique partag√©e"
        ],
        "Model_input": "scope3 transport inbound"
    },
    {
        "Categorie": "Scope3",
        "Sous-categorie": "Dechets",
        "Indicateurs": ["Blocked_stock", "Water_Consumption_PerUnit_L"],
        "Seuils": {"Blocked_stock": "> 5% du total", "Water_Consumption_PerUnit_L": "> P90"},
        "Actions": [
            "Valorisation mati√®re organique (m√©thanisation)",
            "Partnership avec fili√®res de recyclage",
            "Optimisation des process pour r√©duire rebuts",
            "Formation tri √† la source"
        ],
        "Model_input": "scope3 gestion d√©chets"
    },
    {
        "Categorie": "Scope3",
        "Sous-categorie": "Transport_avals",
        "Indicateurs": ["Carbon_Foot_Print_per_Unit_kgCo2", "Supplier_Name"],
        "Seuils": {"Carbon_Foot_Print_per_Unit_kgCo2": "> P90", "Supplier_Name": "== Sans certification environnementale"},
        "Actions": [
            "Optimisation r√©seau distribution",
            "Flotte livraison √©lectrique/v√©lo",
            "Emballages retournables",
            "Calcul CO2 int√©gr√© dans les devis"
        ],
        "Model_input": "scope3 logistique outbound"
    },
    {
        "Categorie": "Scope3",
        "Sous-categorie": "Utilisation_produits",
        "Indicateurs": ["Material_name", "Estimated_Lifetime_Years"],
        "Seuils": {"Material_name": "== Produit p√©rissable", "Estimated_Lifetime_Years": "< 1 an"},
        "Actions": [
            "Eco-conception des produits",
            "Information consommateur sur conservation",
            "Optimisation DLC/DDM",
            "Circularit√© des emballages"
        ],
        "Model_input": "scope3 fin de vie produit"
    },# Score de durabilit√© des fournisseurs
    {
        "Categorie": "Fournisseur",
        "Sous-categorie": "Sustainability_Score",
        "Indicateurs": ["Transport_CO2", "Carbon_Foot_Print_per_Unit_kgCo2", "CO2_Ambient_Level"],
        "Seuils": {"Transport_CO2": "> 300", "Supplier_Sustainability_Score": "< 50"},
        "Actions": [
            "Optimiser les modes de transport (rail/maritime)",
            "Choisir des fournisseurs certifi√©s",
            "Inclure des clauses environnementales dans les contrats",
            "√âvaluer les performances environnementales r√©guli√®rement"
        ],
        "Model_input": "fournisseur impact CO2 transport √©lev√©"
    },

    # KPI CO2 par √©nergie (efficacit√© carbone √©nerg√©tique)
    {
        "Categorie": "Performance",
        "Sous-categorie": "CO2_Par_kW",
        "Indicateurs": ["CO2_Emissions_kg_equipment", "Energy_Consumption_kWh"],
        "Seuils": {"CO2_kg_per_kWh": "> 0.5"},
        "Actions": [
            "Am√©liorer le rendement √©nerg√©tique",
            "Remplacer √©quipements anciens",
            "Ajouter variateurs de fr√©quence",
            "Investir dans la r√©cup√©ration de chaleur"
        ],
        "Model_input": "co2 par kWh √©lev√©"
    },

    # CO2 par mati√®re produite
    {
        "Categorie": "Produit",
        "Sous-categorie": "CO2_Mat√©riel",
        "Indicateurs": ["Carbon_Foot_Print_per_Unit_kgCo2", "Total_Stock"],
        "Seuils": {"CO2_Emissions_Per_Unit_Material_kg": "> 1.5"},
        "Actions": [
            "Changer de fournisseur mati√®re",
            "Utiliser des mat√©riaux recycl√©s",
            "√âvaluer des substituts √† faible empreinte carbone"
        ],
        "Model_input": "co2 mati√®re trop √©lev√©"
    },

    # Water efficiency (eau par unit√©)
    {
        "Categorie": "Eau",
        "Sous-categorie": "Consommation_mati√®re",
        "Indicateurs": ["Water_Consumption_PerUnit_L", "Total_Stock"],
        "Seuils": {"Water_Consumption_Per_Unit_Material": "> 1.0"},
        "Actions": [
            "Changer le proc√©d√© de lavage",
            "R√©utiliser les eaux us√©es",
            "R√©duire les pertes mati√®res"
        ],
        "Model_input": "surconsommation eau mati√®res premi√®res"
    },

    # Quota CO2 d√©pass√©
    {
        "Categorie": "R√©glementation",
        "Sous-categorie": "Quota_CO2",
        "Indicateurs": ["Total_CO2_kg", "Quota"],
        "Seuils": {"Quota_Impact_Pourcentage": "> 100"},
        "Actions": [
            "Arr√™ter temporairement lignes √©nergivores",
            "Acheter cr√©dits carbone (compensation)",
            "R√©viser le mix √©nerg√©tique",
            "Automatiser le suivi en temps r√©el"
        ],
        "Model_input": "d√©passement quota r√©glementaire co2"
    },
    # üì¶ Surstockage = gaspillage + CO2 inutile
    {
        "Categorie": "Stock",
        "Sous-categorie": "Surstockage",
        "Indicateurs": ["Blocked_stock", "Total_Stock"],
        "Seuils": {"Blocked_stock": "> 10% du Total_Stock"},
        "Actions": [
            "R√©duire les cycles d'approvisionnement",
            "Am√©liorer la pr√©vision de la demande",
            "Identifier les mati√®res √† rotation lente"
        ],
        "Model_input": "stock excessif gaspillage co2"
    },
    # üå°Ô∏è Temp√©ratures extr√™mes = d√©rive √©nerg√©tique
    {
        "Categorie": "Environnement",
        "Sous-categorie": "Conditions_ambientes_extremes",
        "Indicateurs": ["Temperature", "Humidity"],
        "Seuils": {"Temperature": "< 5¬∞C ou > 35¬∞C", "Humidity": "< 20% ou > 80%"},
        "Actions": [
            "Installer un monitoring d‚Äôambiance intelligent",
            "Isoler thermiquement les zones critiques",
            "√âviter les plages horaires critiques pour la production"
        ],
        "Model_input": "conditions ambiantes extr√™mes √©nergie"
    },

    # üìâ Sous-performance √©nerg√©tique globale
    {
        "Categorie": "Performance",
        "Sous-categorie": "Efficacit√©_globale_basse",
        "Indicateurs": ["CO2_kg_per_kWh", "Renewable_Energy_Percentage"],
        "Seuils": {"CO2_kg_per_kWh": "> 0.6", "Renewable_Energy_Percentage": "< 20%"},
        "Actions": [
            "Faire un audit √©nerg√©tique global",
            "R√©allouer la production vers des lignes plus efficientes",
            "Simuler l‚Äôimpact d‚Äôun mix √©nerg√©tique renouvelable"
        ],
        "Model_input": "efficacit√© √©nerg√©tique globale faible"
    }, # üßØ Transport longue distance non optimis√©
    {
        "Categorie": "Transport",
        "Sous-categorie": "Distance_non_optimis√©e",
        "Indicateurs": ["Transport_Distance_Km", "Transport_CO2"],
        "Seuils": {"Transport_Distance_Km": "> 800", "Transport_CO2": "> 300"},
        "Actions": [
            "Identifier les points logistiques critiques",
            "Revoir la cha√Æne d‚Äôapprovisionnement",
            "Favoriser les fournisseurs locaux"
        ],
        "Model_input": "transport long co2 fort"
    },
     # üì¶ Mat√©riaux non recyclables dominants
    {
        "Categorie": "Produit",
        "Sous-categorie": "Non_recycl√©",
        "Indicateurs": ["Recycled_Packaging"],
        "Seuils": {"Recycled_Packaging": "== Non"},
        "Actions": [
            "Choix de packaging circulaire",
            "√âvaluation des alternatives recyclables",
            "Normes internes pour l‚Äô√©coconception"
        ],
        "Model_input": "packaging non recycl√©"
    },
    # üö® Alertes de maintenance fr√©quentes
    {
        "Categorie": "Maintenance",
        "Sous-categorie": "Notifications_fr√©quentes",
        "Indicateurs": ["Fk_Date_Creation_Notification", "Fk_Equipment"],
        "Seuils": {"Notifications_par_mois": "> 5"},
        "Actions": [
            "Inspection approfondie des lignes concern√©es",
            "Planification de maintenance pr√©ventive avanc√©e",
            "Analyse causale des d√©faillances"
        ],
        "Model_input": "maintenance trop fr√©quente"
    },
        # üö± Surconsommation d‚Äôeau par unit√©
    {
        "Categorie": "Environnement",
        "Sous-categorie": "Eau_par_unit√©",
        "Indicateurs": ["Water_Consumption_PerUnit_L"],
        "Seuils": {"Water_Consumption_PerUnit_L": "> 1.5"},
        "Actions": [
            "Auditer les cycles de nettoyage",
            "Utiliser des buses √† faible d√©bit",
            "Recyclage interne de l‚Äôeau"
        ],
        "Model_input": "consommation eau excessive par unit√©"
    },
     # üìâ Fournisseur avec score RSE critique
    {
        "Categorie": "Fournisseur",
        "Sous-categorie": "Score_faible",
        "Indicateurs": ["Supplier_Sustainability_Score"],
        "Seuils": {"Supplier_Sustainability_Score": "< 40"},
        "Actions": [
            "Mettre en place une √©valuation trimestrielle",
            "Demander un plan d‚Äôam√©lioration au fournisseur",
            "Chercher des alternatives locales plus durables"
        ],
        "Model_input": "fournisseur score environnement bas"
    }  
]

# Export avec v√©rification des doublons
df_referentiel = pd.DataFrame(problemes_referentiel)
df_referentiel.drop_duplicates(subset=["Categorie", "Sous-categorie", "Model_input"], keep='first', inplace=True)
df_referentiel.to_csv('referentiel_problemes_actions_complet.csv', index=False, encoding='utf-8-sig')

In [24]:
df_referentiel.to_json('file.json', orient='split')

In [28]:
import pandas as pd
import json

# Charger le fichier CSV (ou JSON si tu veux)
df = df_referentiel # √† adapter si JSON

# Nettoyage des colonnes
df.columns = df.columns.str.strip()

# Pr√©paration des lignes JSONL
with open("mistral_finetune.jsonl", "w", encoding="utf-8") as f:
    for _, row in df.iterrows():
        user_prompt = f"Categorie: {row['Categorie']}\nSous-categorie: {row['Sous-categorie']}\nProbl√®me: {row['Model_input']}"

        # G√©rer la liste d'actions proprement
        if isinstance(row["Actions"], str):
            try:
                actions_list = json.loads(row["Actions"].replace("'", '"'))  # corrige les guillemets simples
            except:
                actions_list = [row["Actions"]]
        else:
            actions_list = row["Actions"]

        assistant_response = "\n".join(actions_list)

        # Structure pour le fine-tuning
        message = {
            "messages": [
                {"role": "user", "content": user_prompt},
                {"role": "assistant", "content": assistant_response}
            ]
        }

        f.write(json.dumps(message, ensure_ascii=False) + "\n")

print("‚úÖ Fichier JSONL g√©n√©r√© pour Mistral : mistral_finetune.jsonl")

‚úÖ Fichier JSONL g√©n√©r√© pour Mistral : mistral_finetune.jsonl

## üî∂ Step 3: Semantic Encoding of Problems

### model : all-mpnet-base-v2

Optimized exclusively for English, this model delivers superior precision (+3%) for English-language texts through training on specialized sources (books, scientific articles). It dominates English-language benchmarks (STS-B) but ignores other languages. Perfect for purely English technical or academic applications.

In [32]:
from sentence_transformers import SentenceTransformer, util

# Charger un mod√®le plus puissant (par exemple BERT ou T5)
model = SentenceTransformer('all-mpnet-base-v2')  # Vous pouvez tester d'autres mod√®les de la biblioth√®que SentenceTransformers

# Encodage des textes
referential_texts = [f"{p['Categorie']} {p['Sous-categorie']} {p['Model_input']}" for p in problemes_referentiel]
referential_embeddings = model.encode(referential_texts, convert_to_tensor=True)

### model : paraphrase-multilingual-mpnet-base-v2

This versatile model supports over 50 languages (including French) and excels at multilingual tasks like cross-lingual semantic similarity detection. Trained on aligned datasets (Wikipedia, Common Crawl), it's ideal for international systems or projects combining multiple languages. Its key strength lies in understanding diverse cultural and technical nuances across languages.

In [38]:
from sentence_transformers import SentenceTransformer, util
import re

model = SentenceTransformer('sentence-transformers/paraphrase-multilingual-mpnet-base-v2')

def preprocess_text(text):
    text = re.sub(r'[^\w\s]', '', text.lower())  # Supprime la ponctuation
    return text.strip()

# G√©n√©ration des textes de r√©f√©rence avec correction syntaxique
referential_texts = [
    preprocess_text(
        f"{p['Categorie']} {p['Sous-categorie']} {p['Model_input']} {' '.join(p['Indicateurs'])}"  # Parenth√®se fermante ajout√©e
    ) 
    for p in problemes_referentiel
]

# Encodage des embeddings
referential_embeddings = model.encode(referential_texts, convert_to_tensor=True)

## üî∂ Step 4: User Query via Interactive CLI
The user can ask free-form questions in natural language through a command-line interface (CLI).

Example: "Which equipment consumes too much energy?"

Example: "Problems related to non-recycled materials"

The system:

Encodes the user query using the same BERT model

Compares it to the problem embeddings

Calculates cosine similarity

Returns the top 3 most relevant problems with a confidence score

In [ ]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler

def calculate_dynamic_thresholds(df, problem):
    thresholds = {}
    for indicateur, condition in problem["Seuils"].items():
        if 'P' in condition:
            percentile = float(condition.split('P')[1].split(')')[0])
            thresholds[indicateur] = np.percentile(df[indicateur], percentile)
        elif 'x r√©f√©rence' in condition:
            ref_value = df[indicateur].median()
            thresholds[indicateur] = ref_value * float(condition.split('x')[0].strip())
        elif any(op in condition for op in ['>', '<', '==', '!=']):
            thresholds[indicateur] = condition
        else:
            thresholds[indicateur] = float(re.findall(r'\d+', condition)[0])
    return thresholds

def apply_thresholds(df, problem):
    thresholds = calculate_dynamic_thresholds(df, problem)
    filtered = df.copy()
    
    for indicateur, condition in problem["Seuils"].items():
        try:
            if 'P' in condition:
                filtered = filtered[filtered[indicateur] > thresholds[indicateur]]
            elif 'x r√©f√©rence' in condition:
                filtered = filtered[filtered[indicateur] > thresholds[indicateur]]
            elif any(op in condition for op in ['>', '<', '==', '!=']):
                filtered = filtered.query(f"{indicateur} {condition}")
            else:
                filtered = filtered[filtered[indicateur] > thresholds[indicateur]]
        except Exception as e:
            print(f"Erreur de filtrage pour {indicateur}: {str(e)}")
    return filtered

def find_relevant_problems_with_anomaly_detection(user_query, threshold=0.6):
    query_embedding = model.encode(user_query, convert_to_tensor=True)
    cos_scores = util.cos_sim(query_embedding, referential_embeddings)[0]
    
    results = []
    for idx, score in enumerate(cos_scores):
        if score > threshold:
            results.append({
                **problemes_referentiel[idx],
                "Score": round(float(score), 3)
            })
    
    return sorted(results, key=lambda x: x['Score'], reverse=True)[:3]

def interactive_cli():
    print("""
    ‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ïó‚ñà‚ñà‚ïó   ‚ñà‚ñà‚ïó‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ïó ‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ïó  ‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ïó ‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ïó
    ‚ñà‚ñà‚ïî‚ïê‚ïê‚ïê‚ïê‚ïù‚ïö‚ñà‚ñà‚ïó ‚ñà‚ñà‚ïî‚ïù‚ñà‚ñà‚ïî‚ïê‚ïê‚ñà‚ñà‚ïó‚ñà‚ñà‚ïî‚ïê‚ïê‚ñà‚ñà‚ïó‚ñà‚ñà‚ïî‚ïê‚ïê‚ïê‚ñà‚ñà‚ïó‚ïö‚ïê‚ïê‚ñà‚ñà‚ïî‚ïê‚ïê‚ïù
    ‚ñà‚ñà‚ñà‚ñà‚ñà‚ïó   ‚ïö‚ñà‚ñà‚ñà‚ñà‚ïî‚ïù ‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ïî‚ïù‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ïî‚ïù‚ñà‚ñà‚ïë   ‚ñà‚ñà‚ïë   ‚ñà‚ñà‚ïë   
    ‚ñà‚ñà‚ïî‚ïê‚ïê‚ïù    ‚ïö‚ñà‚ñà‚ïî‚ïù  ‚ñà‚ñà‚ïî‚ïê‚ïê‚ïê‚ïù ‚ñà‚ñà‚ïî‚ïê‚ïê‚ñà‚ñà‚ïó‚ñà‚ñà‚ïë   ‚ñà‚ñà‚ïë   ‚ñà‚ñà‚ïë   
    ‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ïó   ‚ñà‚ñà‚ïë   ‚ñà‚ñà‚ïë     ‚ñà‚ñà‚ïë  ‚ñà‚ñà‚ïë‚ïö‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ïî‚ïù   ‚ñà‚ñà‚ïë   
    ‚ïö‚ïê‚ïê‚ïê‚ïê‚ïê‚ïê‚ïù   ‚ïö‚ïê‚ïù   ‚ïö‚ïê‚ïù     ‚ïö‚ïê‚ïù  ‚ïö‚ïê‚ïù ‚ïö‚ïê‚ïê‚ïê‚ïê‚ïê‚ïù    ‚ïö‚ïê‚ïù   
    """)
    print("Syst√®me expert de d√©tection de probl√®mes industriels\n")
    
    while True:
        try:
            query = input("\nEntrez votre requ√™te (ou 'quit' pour sortir):\n> ")
            
            if query.lower() in ['exit', 'quit', 'q']:
                print("Fin de la session.")
                break
                
            results = find_relevant_problems_with_anomaly_detection(query)
            
            if not results:
                print("\nAucun probl√®me correspondant trouv√©. Essayez avec d'autres termes.")
                continue
                
            print(f"\nüîç R√©sultats pour: '{query}'")
            for i, res in enumerate(results):
                print(f"\n{i+1}. [{res['Categorie']}] {res['Sous-categorie']} (confiance: {res['Score']*100:.1f}%)")
                print("   üìä Indicateurs surveill√©s:", ", ".join(res['Indicateurs']))
                print("   üí° Actions recommand√©es:")
                for j, action in enumerate(res['Actions'][:3]):
                    print(f"      {j+1}. {action}")
                
            if input("\nVoir les donn√©es correspondantes? (o/n) > ").lower() == 'o':
                selected_problem = results[0]
                df_filtered = apply_thresholds(df_merged, selected_problem)
                
                print(f"\nüìà Donn√©es {selected_problem['Categorie']} > {selected_problem['Sous-categorie']}:")
                cols_to_show = ['Equipment_ID', 'Equipment_Name','SupplierCode','Supplier_Name'] + selected_problem["Indicateurs"]
                print(df_filtered[cols_to_show].head().to_string(index=False))
                
        except Exception as e:
            print(f"Erreur: {str(e)}")

# Lancement de l'interface
if __name__ == "__main__":
    interactive_cli()

    ‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ïó‚ñà‚ñà‚ïó   ‚ñà‚ñà‚ïó‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ïó ‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ïó  ‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ïó ‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ïó
    ‚ñà‚ñà‚ïî‚ïê‚ïê‚ïê‚ïê‚ïù‚ïö‚ñà‚ñà‚ïó ‚ñà‚ñà‚ïî‚ïù‚ñà‚ñà‚ïî‚ïê‚ïê‚ñà‚ñà‚ïó‚ñà‚ñà‚ïî‚ïê‚ïê‚ñà‚ñà‚ïó‚ñà‚ñà‚ïî‚ïê‚ïê‚ïê‚ñà‚ñà‚ïó‚ïö‚ïê‚ïê‚ñà‚ñà‚ïî‚ïê‚ïê‚ïù
    ‚ñà‚ñà‚ñà‚ñà‚ñà‚ïó   ‚ïö‚ñà‚ñà‚ñà‚ñà‚ïî‚ïù ‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ïî‚ïù‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ïî‚ïù‚ñà‚ñà‚ïë   ‚ñà‚ñà‚ïë   ‚ñà‚ñà‚ïë
    ‚ñà‚ñà‚ïî‚ïê‚ïê‚ïù    ‚ïö‚ñà‚ñà‚ïî‚ïù  ‚ñà‚ñà‚ïî‚ïê‚ïê‚ïê‚ïù ‚ñà‚ñà‚ïî‚ïê‚ïê‚ñà‚ñà‚ïó‚ñà‚ñà‚ïë   ‚ñà‚ñà‚ïë   ‚ñà‚ñà‚ïë
    ‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ïó   ‚ñà‚ñà‚ïë   ‚ñà‚ñà‚ïë     ‚ñà‚ñà‚ïë  ‚ñà‚ñà‚ïë‚ïö‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ïî‚ïù   ‚ñà‚ñà‚ïë
    ‚ïö‚ïê‚ïê‚ïê‚ïê‚ïê‚ïê‚ïù   ‚ïö‚ïê‚ïù   ‚ïö‚ïê‚ïù     ‚ïö‚ïê‚ïù  ‚ïö‚ïê‚ïù ‚ïö‚ïê‚ïê‚ïê‚ïê‚ïê‚ïù    ‚ïö‚ïê‚ïù

Syst√®me expert de d√©tection de probl√®mes industriels

Entrez votre requ√™te (ou 'quit' pour sortir):
>  transport long co2 fort

üîç R√©sultats pour: 'transport long co2 fort'

1. [Transport] Distance_non_optimis√©e (confiance: 80.9%)
   üìä Indicateurs surveill√©s: Transport_Distance_Km, Transport_CO2
   üí° Actions recommand√©es:
      1. Identifier les points logistiques critiques
      2. Revoir la cha√Æne d‚Äôapprovisionnement
      3. Favoriser les fournisseurs locaux

2. [Fournisseur] Sustainability_Score (confiance: 64.6%)
   üìä Indicateurs surveill√©s: Transport_CO2, Carbon_Foot_Print_per_Unit_kgCo2, CO2_Ambient_Level
   üí° Actions recommand√©es:
      1. Optimiser les modes de transport (rail/maritime)
      2. Choisir des fournisseurs certifi√©s
      3. Inclure des clauses environnementales dans les contrats

Voir les donn√©es correspondantes? (o/n) >  o

üìà Donn√©es Transport > Distance_non_optimis√©e:
Empty DataFrame
Columns: [Equipment_ID, Equipment_Name, SupplierCode, Supplier_Name, Transport_Distance_Km, Transport_CO2]
Index: []

Entrez votre requ√™te (ou 'quit' pour sortir):
>  surconsommation eau

üîç R√©sultats pour: 'surconsommation eau '

1. [Eau] Consommation_mati√®re (confiance: 71.7%)
   üìä Indicateurs surveill√©s: Water_Consumption_PerUnit_L, Total_Stock
   üí° Actions recommand√©es:
      1. Changer le proc√©d√© de lavage
      2. R√©utiliser les eaux us√©es
      3. R√©duire les pertes mati√®res

2. [Environnement] Eau_par_unit√© (confiance: 63.7%)
   üìä Indicateurs surveill√©s: Water_Consumption_PerUnit_L
   üí° Actions recommand√©es:
      1. Auditer les cycles de nettoyage
      2. Utiliser des buses √† faible d√©bit
      3. Recyclage interne de l‚Äôeau

Voir les donn√©es correspondantes? (o/n) >  o

Erreur de filtrage pour Water_Consumption_Per_Unit_Material: name 'Water_Consumption_Per_Unit_Material' is not defined

üìà Donn√©es Eau > Consommation_mati√®re:
Equipment_ID         Equipment_Name SupplierCode           Supplier_Name  Water_Consumption_PerUnit_L  Total_Stock
       E7358 Robot de Palettisation  SUPPLIER_37 Commerce Nature Premier                       1149.0          237
       E7358 Robot de Palettisation  SUPPLIER_37 Commerce Nature Premier                       1149.0          694
       E7358 Robot de Palettisation  SUPPLIER_37 Commerce Nature Premier                       1149.0          748
       E7358 Robot de Palettisation  SUPPLIER_37 Commerce Nature Premier                       1149.0          792
       E7358 Robot de Palettisation  SUPPLIER_37 Commerce Nature Premier                       1149.0          304

In [42]:
import numpy as np
import pandas as pd
import re
from sentence_transformers import SentenceTransformer, util
import torch
import requests

# === Charger mod√®le d'embedding ===
embedding_model = SentenceTransformer("paraphrase-MiniLM-L6-v2")

# === Mistral LLM ===
MISTRAL_API_KEY = "xYaq8vnQzSbmKjZGvnefLa2ugS1jZnj2"
MISTRAL_MODEL_ID = "ft:open-mistral-7b:70f38c7a:20250416:2b82656c"


def ask_mistral_llm(categorie, sous_categorie, query):
    url = "https://api.mistral.ai/v1/chat/completions"
    headers = {
        "Authorization": f"Bearer {MISTRAL_API_KEY}",
        "Content-Type": "application/json"
    }

    prompt = f"""
Tu es un expert en durabilit√© industrielle.

Tu re√ßois une requ√™te li√©e √† un probl√®me : "{query}"
Cat√©gorie : {categorie}
Sous-cat√©gorie : {sous_categorie}

Fournis **au maximum 5 actions correctives ou recommandations** concr√®tes et efficaces, sous forme de liste num√©rot√©e.

Ne donne que les actions (pas de texte introductif ou conclusion).
"""

    data = {
        "model": MISTRAL_MODEL_ID,
        "messages": [
            {"role": "system", "content": "Tu es un expert en durabilit√© industrielle. Tu proposes des actions √©cologiques concr√®tes."},
            {"role": "user", "content": prompt}
        ]
    }

    response = requests.post(url, headers=headers, json=data)
    return response.json()['choices'][0]['message']['content']

In [44]:

def calculate_dynamic_thresholds(df, problem):
    thresholds = {}
    for indicateur, condition in problem["Seuils"].items():
        if 'P' in condition:
            percentile = float(re.findall(r'P(\d+)', condition)[0])
            thresholds[indicateur] = np.percentile(df[indicateur], percentile)
        elif 'x r√©f√©rence' in condition:
            ref_value = df[indicateur].median()
            factor = float(re.findall(r'(\d+(\.\d+)?)', condition)[0][0])
            thresholds[indicateur] = ref_value * factor
        elif any(op in condition for op in ['>', '<', '==', '!=']):
            thresholds[indicateur] = condition
        else:
            thresholds[indicateur] = float(re.findall(r'\d+', condition)[0])
    return thresholds


def apply_thresholds(df, problem):
    thresholds = calculate_dynamic_thresholds(df, problem)
    filtered = df.copy()
    for indicateur, condition in problem["Seuils"].items():
        try:
            if 'P' in condition or 'x r√©f√©rence' in condition:
                filtered = filtered[filtered[indicateur] > thresholds[indicateur]]
            elif any(op in condition for op in ['>', '<', '==', '!=']):
                filtered = filtered.query(f"{indicateur} {condition}")
            else:
                filtered = filtered[filtered[indicateur] > thresholds[indicateur]]
        except Exception as e:
            print(f"Erreur de filtrage pour {indicateur}: {str(e)}")
    return filtered


def find_closest_problem_by_input(query, threshold=0.5):
    referential_texts = [p["Model_input"] for p in problemes_referentiel]
    query_embedding = embedding_model.encode(query, convert_to_tensor=True)
    referential_embeddings = embedding_model.encode(referential_texts, convert_to_tensor=True)
    cos_scores = util.cos_sim(query_embedding, referential_embeddings)[0]
    best_idx = int(torch.argmax(cos_scores))
    if cos_scores[best_idx] > threshold:
        return problemes_referentiel[best_idx]
    return None


def interactive_cli():
    print("""
    ‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ïó‚ñà‚ñà‚ïó   ‚ñà‚ñà‚ïó‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ïó ‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ïó  ‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ïó ‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ïó
    ‚ñà‚ñà‚ïî‚ïê‚ïê‚ïê‚ïê‚ïù‚ïö‚ñà‚ñà‚ïó ‚ñà‚ñà‚ïî‚ïù‚ñà‚ñà‚ïî‚ïê‚ïê‚ñà‚ñà‚ïó‚ñà‚ñà‚ïî‚ïê‚ïê‚ñà‚ñà‚ïó‚ñà‚ñà‚ïî‚ïê‚ïê‚ïê‚ñà‚ñà‚ïó‚ïö‚ïê‚ïê‚ñà‚ñà‚ïî‚ïê‚ïê‚ïù
    ‚ñà‚ñà‚ñà‚ñà‚ñà‚ïó   ‚ïö‚ñà‚ñà‚ñà‚ñà‚ïî‚ïù ‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ïî‚ïù‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ïî‚ïù‚ñà‚ñà‚ïë   ‚ñà‚ñà‚ïë   ‚ñà‚ñà‚ïë   
    ‚ñà‚ñà‚ïî‚ïê‚ïê‚ïù    ‚ïö‚ñà‚ñà‚ïî‚ïù  ‚ñà‚ñà‚ïî‚ïê‚ïê‚ïê‚ïù ‚ñà‚ñà‚ïî‚ïê‚ïê‚ñà‚ñà‚ïó‚ñà‚ñà‚ïë   ‚ñà‚ñà‚ïë   ‚ñà‚ñà‚ïë   
    ‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ïó   ‚ñà‚ñà‚ïë   ‚ñà‚ñà‚ïë     ‚ñà‚ñà‚ïë  ‚ñà‚ñà‚ïë‚ïö‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ïî‚ïù   ‚ñà‚ñà‚ïë   
    ‚ïö‚ïê‚ïê‚ïê‚ïê‚ïê‚ïê‚ïù   ‚ïö‚ïê‚ïù   ‚ïö‚ïê‚ïù     ‚ïö‚ïê‚ïù  ‚ïö‚ïê‚ïù ‚ïö‚ïê‚ïê‚ïê‚ïê‚ïê‚ïù    ‚ïö‚ïê‚ïù   
    """)
    print("Syst√®me expert industriel (LLM + anomalies)\n")

    while True:
        try:
            query = input("\nEntrez votre requ√™te (ou 'quit' pour sortir):\n> ")
            if query.lower() in ['exit', 'quit', 'q']:
                print("Fin de la session.")
                break

            # G√©n√©rer r√©ponse avec Mistral
            print("\nüß† LLM en r√©flexion...")
            mistral_output = ask_mistral_llm("G√©n√©rique", "N/A", query)
            print("\nü§ñ R√©ponse du mod√®le Mistral:\n")
            print(mistral_output)

            # Approximativement retrouver le probl√®me dans le r√©f√©rentiel
            matched_problem = find_closest_problem_by_input(query)
            if matched_problem:
                df_filtered = apply_thresholds(df_merged, matched_problem)
                print(f"\nüìä Donn√©es avec anomalies d√©tect√©es pour {matched_problem['Categorie']} > {matched_problem['Sous-categorie']}")
                print(f"üìå Seuils appliqu√©s: {matched_problem['Seuils']}")
                cols = ['Equipment_ID', 'Equipment_Name', 'Supplier_Name'] + matched_problem['Indicateurs']
                print(df_filtered[cols].head().to_string(index=False))
            else:
                print("\n‚ö†Ô∏è Aucun probl√®me du r√©f√©rentiel d√©tect√© pour l'application des seuils.")

        except Exception as e:
            print(f"Erreur: {str(e)}")


if __name__ == "__main__":
    interactive_cli()

    ‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ïó‚ñà‚ñà‚ïó   ‚ñà‚ñà‚ïó‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ïó ‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ïó  ‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ïó ‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ïó
    ‚ñà‚ñà‚ïî‚ïê‚ïê‚ïê‚ïê‚ïù‚ïö‚ñà‚ñà‚ïó ‚ñà‚ñà‚ïî‚ïù‚ñà‚ñà‚ïî‚ïê‚ïê‚ñà‚ñà‚ïó‚ñà‚ñà‚ïî‚ïê‚ïê‚ñà‚ñà‚ïó‚ñà‚ñà‚ïî‚ïê‚ïê‚ïê‚ñà‚ñà‚ïó‚ïö‚ïê‚ïê‚ñà‚ñà‚ïî‚ïê‚ïê‚ïù
    ‚ñà‚ñà‚ñà‚ñà‚ñà‚ïó   ‚ïö‚ñà‚ñà‚ñà‚ñà‚ïî‚ïù ‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ïî‚ïù‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ïî‚ïù‚ñà‚ñà‚ïë   ‚ñà‚ñà‚ïë   ‚ñà‚ñà‚ïë
    ‚ñà‚ñà‚ïî‚ïê‚ïê‚ïù    ‚ïö‚ñà‚ñà‚ïî‚ïù  ‚ñà‚ñà‚ïî‚ïê‚ïê‚ïê‚ïù ‚ñà‚ñà‚ïî‚ïê‚ïê‚ñà‚ñà‚ïó‚ñà‚ñà‚ïë   ‚ñà‚ñà‚ïë   ‚ñà‚ñà‚ïë
    ‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ïó   ‚ñà‚ñà‚ïë   ‚ñà‚ñà‚ïë     ‚ñà‚ñà‚ïë  ‚ñà‚ñà‚ïë‚ïö‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ïî‚ïù   ‚ñà‚ñà‚ïë
    ‚ïö‚ïê‚ïê‚ïê‚ïê‚ïê‚ïê‚ïù   ‚ïö‚ïê‚ïù   ‚ïö‚ïê‚ïù     ‚ïö‚ïê‚ïù  ‚ïö‚ïê‚ïù ‚ïö‚ïê‚ïê‚ïê‚ïê‚ïê‚ïù    ‚ïö‚ïê‚ïù

Syst√®me expert industriel (LLM + anomalies)

Entrez votre requ√™te (ou 'quit' pour sortir):
>  probleme d'equipement consomation d'energie forte

üß† LLM en r√©flexion...

ü§ñ R√©ponse du mod√®le Mistral:

1. √âvaluation de l'audit d'√©nergie pour identifier les points de consommation d'√©nergie les plus √©lev√©s et les sources d'√©nergie les plus co√ªteuses.
2. Remplacement des √©quipements les plus √©nergivores par des mod√®les plus efficaces ou plus r√©cents.
3. Optimisation de la maintenance des √©quipements pour garantir une bonne performance et une consommation d'√©nergie minimale.
4. Utilisation de syst√®mes de gestion de la charge (load management) pour r√©partir la charge √©lectrique sur une p√©riode plus longue et r√©duire les pics de consommation.
5. Installation de syst√®mes de g√©n√©ration d'√©nergie propre, tels que des panneaux solaires ou des turbines √©oliennes, pour r√©duire la d√©pendance de l'entreprise envers les fournisseurs d'√©nergie fossiles.

üìä Donn√©es avec anomalies d√©tect√©es pour Energie > Solaire
üìå Seuils appliqu√©s: {'Renewable_Energy_Percentage': '< P10', 'Energy_Consumption_kWh': '> P90'}
Equipment_ID         Equipment_Name           Supplier_Name  Renewable_Energy_Percentage  Energy_Consumption_kWh
       E7358 Robot de Palettisation Commerce Nature Premier                         5.31                4407.226
       E7358 Robot de Palettisation Commerce Nature Premier                         5.31                4407.226
       E7358 Robot de Palettisation Commerce Nature Premier                         5.31                4407.226
       E7358 Robot de Palettisation Commerce Nature Premier                         5.31                4407.226
       E7358 Robot de Palettisation Commerce Nature Premier                         5.31                4407.226

Entrez votre requ√™te (ou 'quit' pour sortir):
>  probleme de stock materials

üß† LLM en r√©flexion...

ü§ñ R√©ponse du mod√®le Mistral:

1. Optimisation du stockage : R√©duire les stocks en exc√®s en impl√©mentant un syst√®me de stockage plus efficace et en utilisant des logiciels d'inventaire pour la planification et la gestion des stocks.
2. R√©duction des d√©chets : Optimiser la quantit√© de mat√©riaux utilis√©s en utilisant des outils de conception efficace, en optimisant la production, et en r√©duisant les pertes de mat√©riaux.
3. R√©utilisation et recyclage : R√©utiliser les mat√©riaux usag√©s dans d'autres processus de production, ou les recycler en utilisant des d√©chets comme mati√®re premi√®re.
4. Optimisation des fournisseurs : Rechercher des fournisseurs qui produisent des mat√©riaux durables et qui ont une politique de gestion des d√©chets √©cologiques.
5. √âducation des employ√©s : Former les employ√©s sur les principes de la durabilit√© industrielle, sur la gestion des d√©chets et sur les pratiques de r√©duction de la consommation de mat√©riaux.

‚ö†Ô∏è Aucun probl√®me du r√©f√©rentiel d√©tect√© pour l'application des seuils.

Entrez votre requ√™te (ou 'quit' pour sortir):
>  QUIT

Fin de la session.